name = "SpaceTimeFields"
uuid = "0af78db0-3b7c-4df8-88bd-686b7cc5245d"
authors = ["Jeff Eldredge <jdeldre@g.ucla.edu>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"

[compat]
ForwardDiff = "0.10"
